import Header from "@/components/layout/header/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const figtree = localFont({
  src: [
    {
      path: "./fonts/figtree/Figtree-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/figtree/Figtree-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/figtree/Figtree-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/figtree/Figtree-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/figtree/Figtree-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/figtree/Figtree-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/figtree/Figtree-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-figtree",
  display: "swap", // Рекомендовано використовувати display: swap для кращого UX
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable}  antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
